name: LetsGo
options:
  minimumXcodeGenVersion: 2.38.0
settings:
  base:
    SWIFT_VERSION: 5.9
targets:
  LetsGo:
    type: application
    platform: iOS
    deploymentTarget: "17.0"
    sources:
      - path: LetsGo
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.travelbud.letsgo
        PRODUCT_NAME: LetsGo
        GENERATE_INFOPLIST_FILE: YES
        INFOPLIST_KEY_CFBundleDisplayName: LetsGo
        INFOPLIST_KEY_UILaunchScreen_Generation: YES
        CURRENT_PROJECT_VERSION: 1
        MARKETING_VERSION: 1.0
        SUPPORTS_MACCATALYST: NO
  LetsGoTests:
    type: bundle.unit-test
    platform: iOS
    deploymentTarget: "17.0"
    sources:
      - path: LetsGoTests
    dependencies:
      - target: LetsGo
    settings:
      base:
        GENERATE_INFOPLIST_FILE: YES
schemes:
  LetsGo:
    build:
      targets:
        LetsGo: all
        LetsGoTests: [test]
    run:
      config: Debug
    test:
      config: Debug
      targets:
        - name: LetsGoTests
